org: warleon
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  iam:
    role: arn:aws:iam::407603477016:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
